name: Linux Code Analysis

on: [push, pull_request]

jobs:
  Ubuntu:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        compiler: [gcc, clang]
        include:
          - compiler: gcc
            cc: gcc
            cxx: g++
          - compiler: clang
            cc: clang
            cxx: clang++
    steps:
    - uses: actions/checkout@v4

    - name: Install libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake pkg-config ninja-build ccache libboost-all-dev qtbase5-dev qt5-qmake qtscript5-dev qttools5-dev qttools5-dev-tools qtmultimedia5-dev qtwayland5 libqt5svg5-dev libqt5opengl5-dev libqt5multimedia5-plugins libqt5serialport5-dev libsuperlu-dev liblz4-dev libusb-1.0-0-dev liblzo2-dev libpng-dev libjpeg-dev libglew-dev freeglut3-dev libfreetype6-dev libjson-c-dev libmypaint-dev libopencv-dev libturbojpeg-dev libomp-dev libfuse2 clang-tidy pkg-config

    - name: Set up cache
      run: mkdir -p /home/runner/.ccache

    - uses: actions/cache@v4
      with:
        path: /home/runner/.ccache
        key: ${{ runner.os }}-${{ matrix.compiler }}-${{ github.sha }}
        restore-keys: | 
          ${{ runner.os }}-${{ matrix.compiler }}-
          ${{ runner.os }}-

    - name: Build libtiff
      run: |
        if [ ! -f thirdparty/tiff-4.0.3/libtiff.a ]; then
          cd thirdparty/tiff-4.0.3
          CFLAGS='-fPIC' CXXFLAGS='-fPIC' ./configure --disable-jbig
          make -j $(nproc)
        fi

    - name: Build
      run: |
        export CCACHE_DIR=/home/runner/.ccache
        export CC="ccache ${{ matrix.cc }}"
        export CXX="ccache ${{ matrix.cxx }}"
        cd toonz
        mkdir build
        cd build
        cmake ../sources -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} -DCMAKE_C_COMPILER=${{ matrix.cc }} -DWITH_TRANSLATION=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        ninja

    - name: Run Static Analysis (GCC - Wall) on fixed files
      if: matrix.compiler == 'gcc'
      run: |
        set -e
        echo "Executing static code analysis with GCC on fixed files..."
        INCLUDES=$(grep -oP '(?<=-I)[^ ]+' toonz/build/compile_commands.json | sort | uniq | xargs -I{} echo -I{})
        QT_INCLUDES=$(pkg-config --cflags Qt5Core)

        echo "Files to be analyzed:"
        cat ci-scripts/linux/test_files.txt
        
        while IFS= read -r file; do
          echo "Analyzing file: $file"
          if [ -f "toonz/sources/$file" ]; then
            echo "File exists, running GCC on $file"
            output_file="/tmp/$(basename "$file").log"
            gcc -Wall -Wextra -Werror -v $INCLUDES $QT_INCLUDES "toonz/sources/$file" -o /dev/null 2>&1 | tee "$output_file"
            echo "GCC output for $file saved to: $output_file"
          else
            echo "File $file not found!"
            exit 1
          fi
        done < ci-scripts/linux/test_files.txt

    - name: Run Static Analysis (GCC - Wall) on all files
      if: matrix.compiler == 'gcc'
      run: |
        set -e
        echo "Executing static code analysis with GCC on entire codebase..."
        INCLUDES=$(grep -oP '(?<=-I)[^ ]+' toonz/build/compile_commands.json | sort | uniq | xargs -I{} echo -I{})
        QT_INCLUDES=$(pkg-config --cflags Qt5Core)
        find toonz/sources -name "*.cpp" | xargs gcc -Wall -Wextra -Werror $INCLUDES $QT_INCLUDES -o /dev/null

    - name: Upload GCC logs
      if: matrix.compiler == 'gcc'
      uses: actions/upload-artifact@v3
      with:
        name: gcc-logs
        path: /tmp/*.log

    # Temporarily disable clang-tidy
    # - name: Run Static Analysis (Clang-Tidy)
    #   if: matrix.compiler == 'clang'
    #   run: |
    #     set -e
    #     echo "Executing static code analysis with clang-tidy..."
    #     QT_INCLUDES=$(pkg-config --cflags Qt5Core)
    #     find toonz/sources -name "*.cpp" | xargs clang-tidy -p=toonz/build $QT_INCLUDES

    # Temporarily disable cppcheck
    # - name: Run Static Analysis (Cppcheck)
    #   run: |
    #     set -e
    #     echo "Running static analysis with cppcheck..."
    #     cppcheck --enable=warning,performance,portability --suppress=missingIncludeSystem --force toonz/sources/
