name: Windows Build

on:
  push:
    branches:
      - '*'  # Specify branches where the workflow should run
    paths:
      - '**/*'                                    # Include all files in the repository
      - '!appveyor.yml'                           # Ignore changes in AppVeyor
      - '!README.md'                              # Exclude README
      - '!doc/**'                                 # Exclude documentation
      - '!**/.github/**'                          # Exclude everything in .github folder
      - '.github/workflows/workflow_windows.yml'  # Include Windows workflow file
  pull_request:
    paths:
      - '**/*'
      - '!appveyor.yml'
      - '!README.md'
      - '!doc/**'
      - '!**/.github/**'
      - '.github/workflows/workflow_windows.yml'

jobs:
  Windows:
    runs-on: windows-2022
    env:
      # QT related variable
      QT_PATH: ${{ github.workspace }}\thirdparty\qt\5.15.2_wintab\msvc2019_64  # Path to custom Qt

      # Visual Studio related variables
      MSVCVERSION: "Visual Studio 17 2022"  # Visual Studio version
      
      # Boost-related variables      
      BOOST_TOOLSET: "14.3"                 # Boost MSVC Toolset version
      BOOST_VERSION: "1.87.0"               # Boost version
      BOOST_ROOT: C:\local\boost_1_87_0     # Path to Boost library root
      
      # OpenCV-related variables      
      OPENCV_VERSION: "4.11.0"              # OpenCV version
      OpenCV_DIR: C:\tools\opencv\build     # Path to OpenCV

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false  # Enable LFS to ensure all files are fetched

      # Set up MSVC compiler environment
      - name: Setup MSVC
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cl.exe
        shell: cmd

      # Install clcache via pip
      - name: Install clcache
        run: pip install clcache
        shell: cmd

      # Wrap clcache as cl.exe and add it to PATH
      - name: Wrap clcache as cl.exe
        run: |
          mkdir C:\clcache-wrapper
          copy "C:\hostedtoolcache\windows\Python\3.9.13\x64\Scripts\clcache.exe" C:\clcache-wrapper\cl.exe
          echo C:\clcache-wrapper>> %GITHUB_PATH%
        shell: cmd

      # Confirm clcache is the first cl in path
      - name: Check cl.exe path
        run: |
          where cl
        shell: cmd

      - name: List clcache directory contents before build
        run: |
          echo LOCALAPPDATA=%LOCALAPPDATA%
          IF EXIST "%LOCALAPPDATA%\clcache" (
            dir "%LOCALAPPDATA%\clcache"
          ) ELSE (
            echo clcache folder does not exist yet.
          )
        shell: cmd

      # Print clcache stats before build
      - name: clcache stats before build
        run: clcache -s
        shell: cmd

      - name: List clcache directory contents before build
        run: |
          echo LOCALAPPDATA=%LOCALAPPDATA%
          IF EXIST "%LOCALAPPDATA%\clcache" (
            dir "%LOCALAPPDATA%\clcache"
          ) ELSE (
            echo clcache folder does not exist yet.
          )
        shell: cmd

      - name: List clcache folder before build
        run: |
          echo LOCALAPPDATA=%LOCALAPPDATA%
          dir %LOCALAPPDATA%\clcache || echo clcache folder does not exist yet.
        shell: cmd

      - name: List clcache directory contents after build
        run: |
          echo LOCALAPPDATA=%LOCALAPPDATA%
          IF EXIST "%LOCALAPPDATA%\clcache" (
            dir "%LOCALAPPDATA%\clcache"
          ) ELSE (
            echo clcache folder does not exist yet.
          )
        shell: cmd

      # Cache the clcache directory
      - name: Cache clcache
        uses: actions/cache@v4
        with:
          path: C:/Users/runneradmin/clcache
          key: windows-clcache-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            windows-clcache-

      # Cache OpenCV & Boost installations
      - name: Cache OpenCV & Boost
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            C:\tools\opencv
            ${{ env.BOOST_ROOT }}
          key: ${{ runner.os }}-opencv-boost-${{ env.OPENCV_VERSION }}-${{ env.BOOST_VERSION }}
          restore-keys: |
            ${{ runner.os }}-opencv-boost-

      - name: Install OpenCV & Boost (if cache miss)
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          choco install opencv --version=${{ env.OPENCV_VERSION }} -y
          choco install boost-msvc-${{ env.BOOST_TOOLSET }} --version=${{ env.BOOST_VERSION }} -y
        shell: cmd

      # Download custom Qt build with WinTab support
      - name: Install custom Qt 5.15.2
        run: |
          mkdir thirdparty\qt
          curl -fsSL -o Qt5.15.2_wintab.zip https://github.com/shun-iwasawa/qt5/releases/download/v5.15.2_wintab/Qt5.15.2_wintab.zip
          7z x Qt5.15.2_wintab.zip
          move Qt5.15.2_wintab\5.15.2_wintab thirdparty\qt
        shell: cmd

      - name: Install thirdparty prebuilt libs
        run: |
          curl -fsSL -o thirdparty-libs.zip https://github.com/andeon/opentoonz-thirdparty-libs/releases/download/prebuilt-libs-v1/thirdparty-libs.zip
          7z x -y thirdparty-libs.zip
        shell: cmd

      # Set up MSBuild in PATH
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      # CMake configuration
      - name: Configure CMake
        run: |
          cd thirdparty
          copy /Y tiff-4.0.3\libtiff\tif_config.vc.h tiff-4.0.3\libtiff\tif_config.h
          copy /Y tiff-4.0.3\libtiff\tiffconf.vc.h tiff-4.0.3\libtiff\tiffconf.h
          copy /Y libpng-1.6.21\scripts\pnglibconf.h.prebuilt libpng-1.6.21\pnglibconf.h
          cd ../toonz
          mkdir build
          cd build
          cmake ..\sources -G "%MSVCVERSION%" -Ax64 ^
            -DQT_PATH="%QT_PATH%" ^
            -DBOOST_ROOT="%BOOST_ROOT%" ^
            -DOpenCV_DIR="%OpenCV_DIR%" ^
            -DWITH_WINTAB=Y ^
            -DCMAKE_CXX_COMPILER_LAUNCHER=clcache ^
            -DCMAKE_C_COMPILER_LAUNCHER=clcache
        shell: cmd

      - name: Build OpenToonz
        run: |
          cd toonz\build
          msbuild /p:Configuration=RelWithDebInfo /m /verbosity:minimal ALL_BUILD.vcxproj
        shell: cmd

      # Show clcache stats after build
      - name: clcache stats after build
        run: clcache -s
        shell: cmd

      - name: List clcache folder after build
        run: dir C:\Users\runneradmin\clcache
        shell: cmd

      # Create the package
      - name: Create Package
        run: |
          @echo on
          cd toonz\build
          
          REM Create Opentoonz directory and copy files from RelWithDebInfo
          mkdir Opentoonz
          copy /Y RelWithDebInfo\*.* Opentoonz\
          
          REM Copy required DLLs for proper functionality
          copy /Y ..\..\thirdparty\glut\3.7.6\lib\glut64.dll Opentoonz
          copy /Y ..\..\thirdparty\glew\glew-1.9.0\bin\64bit\glew32.dll Opentoonz
          copy /Y ..\..\thirdparty\libmypaint\dist\64\libiconv-2.dll Opentoonz
          copy /Y ..\..\thirdparty\libmypaint\dist\64\libintl-8.dll Opentoonz
          copy /Y ..\..\thirdparty\libmypaint\dist\64\libjson-c-2.dll Opentoonz
          copy /Y ..\..\thirdparty\libmypaint\dist\64\libmypaint-1-4-0.dll Opentoonz
          
          REM Copy OpenCV DLL (IMPORTANT: Update path/filename when upgrading OpenCV version)
          copy /Y "C:\tools\opencv\build\x64\vc16\bin\opencv_world4110.dll" Opentoonz
          
          REM Deploy Qt dependencies
          "%QT_PATH%\bin\windeployqt.exe" Opentoonz\Opentoonz.exe --opengl
          
          del /Q Opentoonz\*.pdb  REM Remove .pdb files
          del /Q Opentoonz\vc_redist.x64.exe REM Remove vc_redist.x64.exe file
          
          REM Create portablestuff directory and copy stuff folder
          mkdir Opentoonz\portablestuff
          xcopy /Y /E /I ..\..\stuff .\Opentoonz\portablestuff
        shell: cmd

      # Create artifact from the build
      - name: Create Artifact
        run: |
          mkdir artifact
          xcopy toonz\build\Opentoonz artifact\ /E /H /Y
        shell: cmd

      # Upload the generated artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Opentoonz-${{ runner.os }}-${{ github.sha }}
          path: artifact