name: Windows Build

on:
  push:
    branches:
      - '*'  # Specify branches where the workflow should run
    paths:
      - '**/*'                                    # Include all files in the repository
      - '!appveyor.yml'                           # Ignore changes in AppVeyor
      - '!README.md'                              # Exclude README
      - '!doc/**'                                 # Exclude documentation
      - '!**/.github/**'                          # Exclude everything in .github folder
      - '.github/workflows/workflow_windows.yml'  # Include Windows workflow file
  pull_request:
    paths:
      - '**/*'
      - '!appveyor.yml'
      - '!README.md'
      - '!doc/**'
      - '!**/.github/**'
      - '.github/workflows/workflow_windows.yml'

jobs:
  Windows:
    runs-on: windows-2022
    env:
      # QT related variable
      QT_PATH: ${{ github.workspace }}\thirdparty\qt\5.15.2_wintab\msvc2019_64  # Path to custom Qt

      # Visual Studio related variables
      MSVCVERSION: "Visual Studio 17 2022"  # Visual Studio version
      
      # Boost-related variables      
      BOOST_TOOLSET: "14.3"                 # Boost MSVC Toolset version
      BOOST_VERSION: "1.87.0"               # Boost version
      BOOST_ROOT: C:\local\boost_1_87_0     # Path to Boost library root
      
      # OpenCV-related variables      
      OPENCV_VERSION: "4.11.0"              # OpenCV version
      OpenCV_DIR: C:\tools\opencv\build     # Path to OpenCV

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false
      - name: Install and Configure ccache
        run: |
          @echo on
          choco install ccache ninja -y
          copy C:\ProgramData\chocolatey\lib\ccache\tools\ccache*\ccache.exe C:\ProgramData\chocolatey\bin\cl.exe
          mkdir %LOCALAPPDATA%\ccache
        shell: cmd

      # Set up ccache with Visual Studio
      - name: Set ccache with Visual Studio
        run: |
          @echo on
          set CCACHE=C:\ProgramData\chocolatey\bin\ccache.exe
          set CXXCACHE=C:\ProgramData\chocolatey\bin\ccache.exe
        shell: cmd

      # Cache the ccache path
      - name: Set Path ccache
        uses: actions/cache@v4
        with:
          path: C:/Users/runneradmin/AppData/Local/ccache
          key: windows-ccache-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: |
            windows-ccache-${{ github.ref }}-
            windows-ccache-
      # Cache OpenCV and Boost libraries
      - name: Cache OpenCV and Boost
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            C:\tools\opencv
            ${{ env.BOOST_ROOT }}
          key: ${{ runner.os }}-opencv-boost-${{ env.OPENCV_VERSION }}-boost-${{ env.BOOST_VERSION }}
          restore-keys: |
            ${{ runner.os }}-opencv-boost-${{ env.OPENCV_VERSION }}-boost-
      # Install OpenCV and Boost if the cache is missing
      - name: Install OpenCV and Boost if cache is missing
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          @echo on
          choco install opencv --version=${{ env.OPENCV_VERSION }} -y
          choco install boost-msvc-${{ env.BOOST_TOOLSET }} --version=${{ env.BOOST_VERSION }} -y
        shell: cmd

      # Install custom Qt 5.15.2 with WinTab support
      - name: Install custom Qt 5.15.2 with WinTab support
        run: |
          @echo on
          mkdir thirdparty\qt
          curl -fsSL -o Qt5.15.2_wintab.zip https://github.com/shun-iwasawa/qt5/releases/download/v5.15.2_wintab/Qt5.15.2_wintab.zip
          7z x Qt5.15.2_wintab.zip
          move Qt5.15.2_wintab\5.15.2_wintab thirdparty\qt
        shell: cmd

      - name: Install third-party prebuilt libs (LFS workaround)
        run: |
          @echo on
          curl -fsSL -o thirdparty-libs.zip https://github.com/andeon/opentoonz-thirdparty-libs/releases/download/prebuilt-libs-v1/thirdparty-libs.zip
          7z x -y thirdparty-libs.zip
        shell: cmd    

      # Add msbuild to PATH for build process
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      # CMake configuration step
      - name: CMake configuration
        run: |
          @echo on
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64

          cd thirdparty
          copy /Y tiff-4.0.3\libtiff\tif_config.vc.h tiff-4.0.3\libtiff\tif_config.h
          copy /Y tiff-4.0.3\libtiff\tiffconf.vc.h tiff-4.0.3\libtiff\tiffconf.h
          copy /Y libpng-1.6.21\scripts\pnglibconf.h.prebuilt libpng-1.6.21\pnglibconf.h

          cd ../toonz
          mkdir build
          cd build

          cmake ..\sources -G "Ninja" -DQT_PATH="%QT_PATH%" -DBOOST_ROOT="%BOOST_ROOT%" -DOpenCV_DIR="%OpenCV_DIR%" -DWITH_WINTAB=Y
        shell: cmd

      # Build Opentoonz using MSBuild
      - name: Build Opentoonz
        run: |
          @echo on
          cd toonz\build
          cmake --build . --config RelWithDebInfo
        shell: cmd

      # Create the package
      - name: Create Package
        run: |
          @echo on
          cd toonz\build
          
          REM Create Opentoonz directory and copy files from RelWithDebInfo
          mkdir Opentoonz
          copy /Y RelWithDebInfo\*.* Opentoonz\
          REM Copy required DLLs for proper functionality
          copy /Y ..\..\thirdparty\glut\3.7.6\lib\glut64.dll Opentoonz
          copy /Y ..\..\thirdparty\glew\glew-1.9.0\bin\64bit\glew32.dll Opentoonz
          copy /Y ..\..\thirdparty\libmypaint\dist\64\libiconv-2.dll Opentoonz
          copy /Y ..\..\thirdparty\libmypaint\dist\64\libintl-8.dll Opentoonz
          copy /Y ..\..\thirdparty\libmypaint\dist\64\libjson-c-2.dll Opentoonz
          copy /Y ..\..\thirdparty\libmypaint\dist\64\libmypaint-1-4-0.dll Opentoonz
          
          REM Copy OpenCV DLL (IMPORTANT: Update path/filename when upgrading OpenCV version)
          copy /Y "C:\tools\opencv\build\x64\vc16\bin\opencv_world4110.dll" Opentoonz
          
          REM Deploy Qt dependencies
          "%QT_PATH%\bin\windeployqt.exe" Opentoonz\Opentoonz.exe --opengl
          
          del /Q Opentoonz\*.pdb  REM Remove .pdb files
          del /Q Opentoonz\vc_redist.x64.exe REM Remove vc_redist.x64.exe file
          
          REM Create portablestuff directory and copy stuff folder
          mkdir Opentoonz\portablestuff
          xcopy /Y /E /I ..\..\stuff .\Opentoonz\portablestuff
        shell: cmd

      # Create artifact from the build
      - name: Create Artifact
        run: |
          mkdir artifact
          xcopy toonz\build\Opentoonz artifact\ /E /H /Y
        shell: cmd

      # Upload the generated artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Opentoonz-${{ runner.os }}-${{ github.sha }}
          path: artifact